--- #YAML:1.0
name:               CGI-Enurl
version:            1.08
abstract:           Encode strings, arrays and hashes so that they may be appended to URLs as queries
author:
    - Jan Krynicky (Jenda@Krynicky.cz)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
